@startuml need_to_find_id

    abstract class Node {
        +swhid : String
    }



    class ContentHashes {
       + blake2s256 : String
       + sha1 : String
       + sha1_git : String
       + sha256 : String
    
    }
    class Content extends Node{
        + length : String
        + status : String
    
    }
    Content "1" *-- "1" ContentHashes
    class Directory extends Node {
    }

    class DirectoryEntry {
        + name : String
    }
    class Revision extends Node {
        +message : String
        +author : String
        +date : DateTime
        +committer : String
        +committerDate : DateTime
    }
    Revision "*" o-- "1" Directory

    class Release extends Node{
        + date : DateTime
        + author : String
        + name : String
        + message : String
    
    }

    Release "*" o-- "1" Revision

    class SnapshotBranch {
      + name : String
    }
    class Snapshot extends Node{
    }
    Snapshot "*" o-- "*" Release
    Snapshot "*" o-- "*" Revision

    (Snapshot,Release) . SnapshotBranch
    (Snapshot,Revision) . SnapshotBranch

    class OriginVisit {
       +visit : int
       +date : DateTime
       +originType : String
       +status : String
    }
    class Origin extends Node {
        +origin : String
    }
    Origin "1" o-- "*" Snapshot
    (Origin,Snapshot) . OriginVisit




Directory "*" o-- "*" Content
Directory "*" o-- "*" Revision
Directory "*" o-- "*" Directory




(Directory, Content) . DirectoryEntry
(Directory, Directory) . DirectoryEntry
(Directory, Revision) . DirectoryEntry


@enduml