name: Build

on:
  push:
  pull_request:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Install dependencies
        run: |
          cd scripts
          sh install_swh_graph_to_local_m2.sh
      - name: Build with Maven
        run: mvn  --no-transfer-progress clean package

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      - name: Uber jar of the build
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: target/shTest*.jar
